name: agino_mobile
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.9.0
  lorem_ipsum: ^0.0.3
  dots_indicator: ^3.0.0
  country_picker: ^2.0.20
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.2.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
